/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.CwsPlanning
{
    public class TrafficLight : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "hrca_decision/TrafficLight";

        public int block_selected;
        public int block_status;
        public int zone_selected;
        public int zone_status;

        public TrafficLight()
        {
            this.block_selected = 0;
            this.block_status = 0;
            this.zone_selected = 0;
            this.zone_status = 0;
        }

        public TrafficLight(int block_selected, int block_status, int zone_selected, int zone_status)
        {
            this.block_selected = block_selected;
            this.block_status = block_status;
            this.zone_selected = zone_selected;
            this.zone_status = zone_status;
        }
    }
}
